config/routes.rb
Rails.application.routes.draw do

  get 'terms' =>'terms#index'

  get 'completed' =>'completed#index'

  root 'student#index'

  post 'student/create' => 'student#create'

end

app/models/student.rb
class Student < ActiveRecord::Base

  validates :name, presence: {message: "es requerido"}
  validates :surname, presence: {message: "es requerido"}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: {message: "es requerido"}, uniqueness: {case_sensitive: false, message: "ya está registrado"},
            format: { :with => VALID_EMAIL_REGEX , message: "no tiene un formato válido" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/completed_controller.rb
class CompletedController < ApplicationController
  def index
    if flash[:redirect] != "by_student_created"
      redirect_to root_path
    end
  end
end

app/controllers/student_controller.rb
require 'unirest'

class StudentController < ApplicationController

  def index
    @new_student=Student.new
    @students_count=Student.count
  end

  def create

    @new_student=Student.new(params[:new_student].permit(:name, :surname, :email))
    if @new_student.save
      append_to_sheet(@new_student.name+" "+@new_student.surname, @new_student.email)
      flash[:redirect] ="by_student_created"
      redirect_to completed_path
    else
      render action: 'index'
    end

  end

  private
  def append_to_sheet(name, email)
    response = Unirest.post ENV["GRADUATION_MAKER"],
                            headers:{ "Accept" => "application/json" },
                            parameters:{ :value1=>name, :value2=>email }

  end



end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_helper.rb
module CompletedHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/completed/index.html.erb
<% content_for :title, "¡Oído cocina! A la Graduation Party que te vas" %>


<div class="container">
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="https://www.mckendree.edu/offices/academic-records/grad-information/senior-invite.png">
    </div>
    <div class="card-content">
      <h5 class="card-titlegrey-text text-darken-4">¡Lo hemos entendido!</h5>
      <p>Estamos muy contentos de que vengas 😊</p>

      <div class="center-align">
        <%= button_to 'Volver', root_path,  :method => "get",class: "btn-large waves-effect waves-light purple" %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div class="footer-copyright">
  <div class="row container">
    © 2016 Zombispormedio
    <%= link_to "Github", "https://github.com/Zombispormedio/graduation", :target => "_blank", :class => "right" %>
  </div>
</div>

</body>
</html>

app/views/student/_form.html.erb
<div class="row">
  <%= form_for :new_student, :html => {:class => "col s12"}, url: student_create_path do |f| %>
      <div class="row">
        <div class="input-field col s6">
          <%= f.label :name, 'Nombre' %><br>
          <%= f.text_field :name, :required => true %>
        </div>
        <div class="input-field col s6">
          <%= f.label :surname, 'Apellido' %><br>
          <%= f.text_field :surname, :required => true %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">

          <p>
            <%= f.label :email %><br>
            <%= f.email_field :email, :required => true %>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="row center-align">
          <%= submit_tag 'No me lo pierdo', class: "btn-large waves-effect waves-light purple" %>
        </div>

        <div class="row center-align">
          <%= link_to "Si vienes, aceptas los términos y condiciones del uso de tus datos", terms_path, :target => "_blank" %>
        </div>
      </div>


      <% if @new_student.errors.any? %>
          <div>
            <h5>¡Uy! ¿Qué ha podido pasar?</h5>
            <p><%= pluralize(@new_student.errors.count, "error") %></p>

            <ul>
              <% @new_student.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      </div>
  <% end %>
  </div>

app/views/student/index.html.erb
<% content_for :title, "Bienvenido a la Multimedia Graduation Party" %>
<div class="center-align">
  <h1>Bienvenido a la Graduation Party</h1>
  <h3>¿Quieres asistir?</h3>
  <p>Sólo para «Multimedianos» graduados o de quinto. Ya somos <strong><%= @students_count %></strong> que vamos.</p>
</div>
<div class="container">
  <%= render 'form' %>
</div>

app/views/terms/index.html.erb
<% content_for :title, "Términos y condiciones" %>
<div class="container center-align">
  <h3>Términos y condiciones</h3>
  <div class="row">
    <h5>Porque somos gente seria y hacemos las cosas bien</h5>
  </div>
</div>
<ul class="container" id="terms-list">
  <li class="row">Cuando el evento finalice, la base de datos dispuesta para el evento, que contiene sus datos
    personales, será borrada y dada baja de servicio.
  </li>
  <li class="row">Acepta el uso de su email para el envío y recepción de newsletters que contengan
    información relevante y relacionada al evento. Cualquier newsletter sólo será enviada antes del evento.
    Es posible que no sea necesario enviar ninguna newsletter, pero por si acaso se hace constar en los términos y
    condiciones.
  </li>

</ul>


<div class="center-align down">
  <%= button_to 'Volver', root_path, :method => "get", class: "btn-large waves-effect waves-light purple" %>
</div>